# Copyright (c) 2021 Nick Winans
# SPDX-License-Identifier: MIT

# Uncomment to enable USB logging
# CONFIG_ZMK_USB_LOGGING=y

# Enable deep sleep mode
CONFIG_ZMK_SLEEP=y

# Set deep sleep timeout to 15 minutes (900,000 milliseconds)
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000

# Turn off RGB underglow on boot to preserve battery power
CONFIG_ZMK_RGB_UNDERGLOW_ON_START=n
